site_name: Reincarnation+#Tech
repo_url: https://github.com/fereria/reincarnation_tech
site_url: https://fereria.github.io/reincarnation_tech/
site_author: Megumi Ando@Remiria

theme:
  favicon: "favicon.ico"
  custom_dir: "theme"
  language: ja
  name: material
  palette:
    accent: Green
    primary: Green
  features:
    - tabs
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fereria
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fereria
    - icon: fontawesome/solid/bookmark
      link: https://zenn.dev/remiria

extra_css:
  - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

google_analytics:
  - UA-134257918-1
  - auto

plugins:
  - drawio-exporter:
      # Diagrams are cached to speed up site generation. The default path is
      # drawio-exporter, relative to the documentation directory.
      cache_dir: "drawio-exporter"
      # Path to the Draw.io executable:
      #   * drawio on Linux
      #   * draw.io on macOS
      #   * or draw.io.exe on Windows
      # We'll look for it on your system's PATH, then default installation
      # paths. If we can't find it we'll warn you.
      drawio_executable: null
      # Additional Draw.io CLI args
      drawio_args: ["--no-sandbox"]
      # Output format (see draw.io --help | grep format)
      format: svg
      # Embed format
      #   * The default is to embed via the <img> tag, only rewriting the
      #     value of the src attribute.
      #   * Consider <object type="image/svg+xml" data="{img_src}"></object>
      #     to enable interactive elements (like hyperlinks) in SVGs.
      embed_format: "{img_open}{img_src}{img_close}"
      # Glob pattern for matching source files
      sources: "*.drawio"
  - git-revision-date-localized:
      type: iso_datetime
  - search:
      lang:
        - en
        - ja
  - awesome-pages
  - macros
  - mdoctag:
      tagpage_dir: "tags"
      data_filename: "tags.json"
  - rss

markdown_extensions:
  - hbfm.quote_uri_hash
  - hbfm.inline_coloring
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - markdown.extensions.nl2br
  - fontawesome_markdown
  - def_list
  - admonition
  - meta
  - footnotes
  - pymdownx.critic
  - markdown_blockdiag:
      format: svg
  - toc:
      permalink: "Â¶"
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.highlight:
      linenums: true
